# Generated by Django 5.1.1 on 2024-11-02 22:06

import TP_DECOM_SD.EnvioDoc.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autores', models.CharField(max_length=255)),
                ('resumo', models.TextField()),
                ('palavras_chave', models.CharField(max_length=255)),
                ('data_publicacao', models.PositiveIntegerField(validators=[TP_DECOM_SD.EnvioDoc.models.validar_ano])),
                ('revista', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='documentos/')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalDocumento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autores', models.CharField(max_length=255)),
                ('resumo', models.TextField()),
                ('palavras_chave', models.CharField(max_length=255)),
                ('data_publicacao', models.PositiveIntegerField(validators=[TP_DECOM_SD.EnvioDoc.models.validar_ano])),
                ('revista', models.CharField(max_length=255)),
                ('arquivo', models.TextField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical documento',
                'verbose_name_plural': 'historical documentos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
