# Generated by Django 5.1.1 on 2024-11-03 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvioDoc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='autores',
        ),
        migrations.RemoveField(
            model_name='historicaldocumento',
            name='autores',
        ),
        migrations.AddField(
            model_name='documento',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_criados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='equipe',
            field=models.ManyToManyField(blank=True, related_name='equipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldocumento',
            name='autor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
