# Generated by Django 5.1.1 on 2024-11-02 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnvioDoc', '0002_historicaldocumento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='autores',
        ),
        migrations.RemoveField(
            model_name='historicaldocumento',
            name='autores',
        ),
    ]
